### ISSUE TITLE
Can't save preferences

### ISSUE THREAD

**Issue by jodyheavener** [jodyheavener/N1-Thread-Age#1]
Hey @jackiehluo I used your [n1-weather plugin](https://github.com/jackiehluo/n1-weather) as a boilerplate for this project. Thank you!

I haven't been able to figure out how to save settings using a `NylasStore`. If you have a minute, think you could point me in the right direction?

**Comment by jackiehluo** [comment]
@jodyheavener Do you mean persisting a setting through restarts of the app? What kind of setting are we talking?

**Comment by jodyheavener** [comment]
Oh sorry - yeah! I'd to persist through restarts. Right now I'm extending NylasStore, just not sure how to set up the [constructor](https://github.com/jodyheavener/N1-Thread-Age/blob/master/lib/thread-age-store.jsx#L6).

**Comment by jackiehluo** [comment]
So stores won't work that way—they just store the state for the period of the session. You would need to add the setting to a JSON file somewhere. The `config.json` is usually a good place for settings—I think you should be able to update that with `NylasEnv.config.set(KEY, VALUE)`.

**Comment by jodyheavener** [comment]
Thanks! Will give it a go.

**Comment by jodyheavener** [comment]
Fixed in https://github.com/jodyheavener/N1-Thread-Age/commit/cbafc819ff41a00933122178c0ff0bdcd5e510ea
